token_auth.access_token_resource.*:
  type: config_entity
  label: 'Access Token Resource config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    locked:
      type: boolean
      label: 'Locked'
    permissions:
      type: sequence
      label: 'Permissions'
      sequence:
          type: string
    uuid:
      type: string
