token_auth.access_token_scope.*:
  type: config_entity
  label: 'Access Token Scope config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    locked:
      type: boolean
      label: 'Locked'
    uuid:
      type: string
